### ISSUE TITLE
System.NullReferenceException - FendragonBCS\src\Systems\HarmonyPatches\EntityPlayer_LightHsv_Patch.cs:line 35

### ISSUE THREAD

**Issue by Ilappy666** [UA-Shaman/FendragonBCS#3]
Running on 64 bit Windows 10.0.22631.0 with 61333 MB RAM
Game Version: v1.19.8 (Stable)
2024-08-07 02:57:45: Critical error occurred in the following mod: fendragonbcs@0.0.4
Loaded Mods: aculinaryartillery@1.1.5, arrowrecovery@1.0.0, chiseltools@1.12.3, Clothez@1.0.0, hqzlights@1.1.1, driftersbelongunderground@1.0.1, fantasycreatures@0.7.1, HumanSkinTones@0.0.3, longtermfood@0.0.2, millwright@1.1.6, moremolds@1.4.2, noisybears@1.1.0, TA_plainsandvalleys@1.0.5, primitivesurvival@3.6.4, richerthandirt@1.2.1, sca@1.0.1, speararrowheadbits@1.1.0, visibleore@1.0.1, game@1.19.8, wlts@1.0.0, ancienttools@1.5.18, egocaribautomapmarkers@3.1.0, betterfirepit@1.1.4, betterruins@0.3.7, butchering@1.6.5, carryon@1.7.4, commonlib@2.5.0-rc.2, expandedfoods@1.6.9, fendragonbcs@0.0.4, fromgoldencombs@1.6.0, greenbegone@1.0.0, hudclock@3.4.0, lichenredux@1.8.3, medievalexpansion@3.13.1, nakedafraid@1.0.1, prospecttogether@1.3.0, rivers@3.1.0, stonebakeoven@1.1.3, vhfp@1.1.0, creative@1.19.8, survival@1.19.8, workbenchexpansion@1.8.0, xlib@0.8.6, helvehammerext@1.6.0, RedDyeFromBerries@1.1.1, stonequarry@3.3.1, xskills@0.8.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at FendragonBCS.EntityPlayer_LightHsv_Patch.Postfix(Byte[]& __result, EntityPlayer __instance) in D:\VSCode\Repos\Commisions\FendragonBCS\src\Systems\HarmonyPatches\EntityPlayer_LightHsv_Patch.cs:line 35
   at Vintagestory.API.Common.EntityPlayer.get_LightHsv_Patch3(EntityPlayer this)
   at Vintagestory.Client.NoObf.SystemRenderPlayerEffects.<>c.<onBeforeRender>b__8_0(Entity e) in VintagestoryLib\Client\Systems\Render\RenderEffectsAndDynLights.cs:line 49
   at Vintagestory.Common.GameMain.GetEntitiesAround(Vec3d position, Single horRange, Single vertRange, ActionConsumable`1 matches) in VintagestoryLib\Common\GameMain.cs:line 244
   at Vintagestory.Client.NoObf.SystemRenderPlayerEffects.onBeforeRender(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Ilappy666** [comment]
Im using 2 linen mini backpacks, a v. tin bronze and a v. copper
It must be missing a triangle

**Comment by UA-Shaman** [comment]
The problem is solved, as it were )

**Comment by Anarevian** [comment]
Hey 
after multiple crashes with roughly the same log which Ilappy666 posted here I wanted to throw my crash log in the race too as this is happening for me too multiple times a day and i cannot figure out why.

Running on 64 bit Windows 10.0.19045.0 with 65436 MB RAM
Game Version: v1.19.8 (Stable)
23/11/2024 20:40:15: Critical error occurred in the following mod: fendragonbcs@0.0.9
Loaded Mods: advancedsmithing@1.3.0, bettercrates@1.7.1, Bluesky@1.1.0, chiseltools@1.12.10, claybrickforming@1.0.0, fancysky@1.1.6, fixedpaths@1.0.1, honeypressmittim@1.0.2, millwright@1.1.7, moreicons_cs@1.1.0, moreclay@1.0.2, moredrifterloot@1.5.4, noarmorhunger@1.0.0, noclassnegatives@1.0.0, orepulverizer@1.1.1, smokychimneys@1.0.0, toolsextended@1.1.0, translocatorengineeringredux@1.5.3, viesblocks@2.4.12, viescraftmachines@2.3.2, game@1.19.8, vtr@4.0.4, wlts@1.0.0, altmapiconrenderer@1.2.2, animationmanagerlib@0.8.8, egocaribautomapmarkers@3.1.0, betterfirepit@1.1.4, betterruins@0.3.9, carryon@1.7.4, charcoalpitdoor@1.0.0, chickenfeed@1.1.3, commonlib@2.5.0-rc.2, composter@1.1.0, danatweaks@3.2.4, fendragonbcs@0.0.9, foodshelves@1.4.1, fromgoldencombs@1.6.3, heatretention@1.0.2, herbarium@1.3.0, hit@2.2.0, jopainting@1.4.0, kscartographytable@1.0.1, medievalexpansion@3.13.1, noticeboard@1.0.0, oneroof@1.2.2, particlesplus@1.1.0, paxel@1.5.0, pelaguswinds@1.0.0, pigfeed@1.0.4, prospecttogether@1.4.0-rc.2, sailboat@1.3.1, sheepfeed@1.0.0, simpletailoring@1.1.2, storagecontroller@1.0.11, th3dungeon@0.2.1, vanvar@5.0.4, vs-discordrpc@1.0.0, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, xlib@0.8.6, bullseye-continued@2.5.8, configlib@1.3.13, extraoverlays@1.4.0, sleekdoorglass@1.0.0, playercorpse@1.10.1-rc.1, stonequarry@3.3.1, th3dungeontopentrance@0.1.1, wildcrafttree@1.2.0, xinvtweaks@1.6.6, xskills@0.8.8, statushudcont@2.1.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at FendragonBCS.EntityPlayer_LightHsv_Patch.Postfix(Byte[]& __result, EntityPlayer __instance) in F:\VSCode\Repos\Commisions\FendragonBCS\src\Systems\HarmonyPatches\EntityPlayer_LightHsv_Patch.cs:line 35
   at Vintagestory.API.Common.EntityPlayer.get_LightHsv_Patch3(EntityPlayer this)
   at Vintagestory.Client.NoObf.SystemRenderPlayerEffects.<>c.<onBeforeRender>b__8_0(Entity e) in VintagestoryLib\Client\Systems\Render\RenderEffectsAndDynLights.cs:line 49
   at Vintagestory.Common.GameMain.GetEntitiesAround(Vec3d position, Single horRange, Single vertRange, ActionConsumable`1 matches) in VintagestoryLib\Common\GameMain.cs:line 244
   at Vintagestory.Client.NoObf.SystemRenderPlayerEffects.onBeforeRender(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by UA-Shaman** [comment]
This error fix in new version mod. Thx.
